### ISSUE TITLE
The explorer crashes when there are any `bigint` values

### ISSUE THREAD

**Issue by dahlia** [hashrock/kivi#6]
The explorer crashes with the following error message when there are any `bigint` values in the KV database:

```
2024-02-25 16:20:10.717 [error] Error: Failed to list items: Do not know how to serialize a BigInt
    at g.value (/Users/dahlia/.vscode/extensions/hashrock.deno-kv-admin-0.0.5/out/kv/webview.js:101:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The error message apparently is thrown by `JSON.stringify()`:

```
> JSON.stringify(1n)
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at <anonymous>:1:27
```

**Comment by AbdulrhmanGoni** [comment]
> The explorer crashes with the following error message when there are any `bigint` values in the KV database:
> 
> ```
> 2024-02-25 16:20:10.717 [error] Error: Failed to list items: Do not know how to serialize a BigInt
>     at g.value (/Users/dahlia/.vscode/extensions/hashrock.deno-kv-admin-0.0.5/out/kv/webview.js:101:23)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> The error message apparently is thrown by `JSON.stringify()`:
> 
> ```
> > JSON.stringify(1n)
> Uncaught TypeError: Do not know how to serialize a BigInt
>     at JSON.stringify (<anonymous>)
>     at <anonymous>:1:27
> ```

Hi @dahlia

this extention is no longer working or being maintained.

If you are still using Deno KV or interesting in it, check this alternative solution out:

It's a desktop app that allows you to browse and perform CRUD operations on your Deno KV databases (local or remote) through a nice UI 

Here is the [app](https://abdulrhmangoni.github.io/denokv-gui-client/)
